version: '3.8'

services:
  db:
    image: mysql:latest
    # volumes:
      # - db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=ujian
    ports:
      - "3306:3306"
    command: free -s 2 -c 30
    networks:
      - app-network

  app:
    stdin_open: true
    tty: true
    image: myapp:latest
    # build:
      # context: .
      # dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      db
    # command: ["sh", "-c", "sleep 60 && ./main"]
    networks:
      - app-network

# volumes:
  # db-data:

networks:
  app-network:
